version: "3.9"

services:
  flask_api:
    build: .
    container_name: flask_api
    ports:
      - "5000:5000"
    env_file:
      - .env.prod
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - flask_api
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

